tasks/urls.py
from django.urls import path
from . import views
app_name='tasks'
urlpatterns = [
    path('', views.index,name='index'),
    path('update_task/<str:pk>/', views.updateTask,name='updateTask'),
    path('delete_task/<str:pk>/', views.deleteTask,name='deleteTask'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls'))
]

tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model): 
    title    = models.CharField(max_length=50)
    complete = models.BooleanField(default=False)
    created  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title 
    

tasks/forms.py
from django import forms
from .models import *
class TaskForm(forms.ModelForm):    
    title=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Add new task'}))
    class Meta:
        model = Task 
        fields = "__all__"

tasks/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *
def index(request):
    if request.method == "POST":
        form=TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = TaskForm()
    tasks=Task.objects.all()
    contex={'tasks':tasks,'form':form}
    return render(request,'tasks/list.html',contex)
def updateTask(request,pk):
    task = Task.objects.get(pk=pk)
    if request.method == "POST":
        form=TaskForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
         form = TaskForm(instance=task)
    context={'form':form}
    return render(request,'tasks/update_task.html',context)
def deleteTask(request,pk):
    item=Task.objects.get(id=pk)
    if request.method=='POST':
        item.delete()
        return redirect('/')
    context={'item':item}
    return render(request,'tasks/delete_task.html',context)

tasks/templates/tasks/delete_task.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href=" {% static 'tasks/aa.css' %} ">
<p>Are you sure you want to delete " {{item}} "</p>

<a class="btn btn-sm btn-info" href=" {% url 'tasks:index' %} ">cancel</a>
<form action="" method="post">
    {% csrf_token %}
    <button  class="btn btn-sm btn-danger" type="submit">delete</button>
    
</form>

tasks/templates/tasks/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'tasks/aa.css' %} ">
<div class="center-column">
    <form action="" method="post">
        {% csrf_token %}
        {{form.title}}
        <input class="btn btn-info " type="submit" value="create">
    </form>
    <div class="todo-list" >
    {% for i in tasks %}
        <div class="item-row">
            {% if i.complete == True %}
                <strike>{{ i }}</strike>
            {% else %}
                <span>{{ i }}</span>
            {% endif %}
            <a class="btn btn-sm btn-info" href="{% url 'tasks:updateTask' i.pk %}">update</a>
            <a class="btn btn-sm btn-danger" href="{% url 'tasks:deleteTask' i.pk %}">delete</a>
            

                
        </div>
    {% endfor %}
</div>
</div>
</body>
</html>

tasks/templates/tasks/update_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'tasks/aa.css' %} ">
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="update" name="update-task">
    </form>
</body>
</html>